"""
Layer 1 - Semantic Risk Engine (Cohere Embed English v3).

Replaces regex keyword matching with cosine-similarity scoring against
pre-computed reference embeddings for each risk category.  This approach
captures paraphrased and semantically equivalent language that exact-match
patterns would miss.

Dependencies: boto3 (pre-installed in the Lambda runtime).
"""

import json
import logging
import os
import time
import random
from typing import List, Optional, Tuple

import boto3

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

_REGION = os.environ.get("AWS_REGION", "us-east-1")
EMBEDDING_MODEL_ID: str = os.environ.get(
    "EMBEDDING_MODEL_ID", "cohere.embed-english-v3"
)
REFERENCE_CACHE_BUCKET: Optional[str] = os.environ.get("REFERENCE_CACHE_BUCKET")
REFERENCE_CACHE_KEY: str = "_cache/reference_embeddings.json"

# Path to the pre-computed embeddings file bundled with the Lambda package.
# Generated by scripts/precompute_embeddings.py - eliminates cold-start Titan calls.
_BUNDLED_EMBEDDINGS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "reference_embeddings.json"
)

# ---------------------------------------------------------------------------
# Risk category definitions
# Each category has a calibrated weight and a rich reference description.
# Titan encodes the semantic meaning of the reference; the document is then
# scored by how similar its embedding is to each reference embedding.
# Combined weights sum to 1.0.
# ---------------------------------------------------------------------------
RISK_CATEGORIES: dict = {
    "financial_fraud": {
        "weight": 0.25,
        "reference": (
            "Financial fraud involving money laundering, embezzlement, bribery, "
            "corruption, misappropriation of funds, fictitious transactions, shell "
            "companies, hidden accounts, unauthorized fund transfers, kickbacks, "
            "and falsification of financial records or statements."
        ),
    },
    "securities_violation": {
        "weight": 0.25,
        "reference": (
            "Securities violations including insider trading on material non-public "
            "information, market manipulation, pump and dump schemes, front running, "
            "wash trading, naked short selling, spoofing, misrepresentation of "
            "investment securities, and failure to disclose material information."
        ),
    },
    "data_privacy": {
        "weight": 0.15,
        "reference": (
            "Data privacy violations including GDPR non-compliance, personal data "
            "breaches, unauthorized access to sensitive information, PII exposure, "
            "HIPAA violations, CCPA non-compliance, unencrypted data transmission, "
            "and unauthorized data exfiltration or sharing."
        ),
    },
    "operational_risk": {
        "weight": 0.15,
        "reference": (
            "Operational compliance failures including regulatory breaches, audit "
            "failures, internal control failures, policy violations, sanctions "
            "violations, anti-money laundering failures, know-your-customer failures, "
            "suspicious activity, unusual transactions, and transaction structuring "
            "to avoid regulatory reporting requirements."
        ),
    },
    "concealment_indicators": {
        "weight": 0.20,
        "reference": (
            "Concealment of misconduct including requests for off-the-record "
            "communications, instructions to delete messages or destroy evidence, "
            "covering up regulatory violations, bypassing internal controls, "
            "circumventing audit processes, avoiding documentation, undocumented "
            "payments, and informal arrangements to hide improper activities."
        ),
    },
}

# ---------------------------------------------------------------------------
# Scoring constants
#
# Cohere Embed English v3 produces cosine similarities in roughly [0.30, 0.95]
# for compliance text.  _SIMILARITY_BASELINE subtracts the expected background
# level so that unrelated documents contribute ~0 to the score.
# _SIMILARITY_SCALE amplifies the remaining signal so that a single category
# with high similarity (≥ 0.80) can breach the default RISK_THRESHOLD of 0.35.
#
# Tuning guide:
#   • Raise _SIMILARITY_BASELINE → fewer false positives, more false negatives.
#   • Lower _SIMILARITY_BASELINE → opposite.
#   • RISK_THRESHOLD (handler env var, default 0.35) is the final gate.
# ---------------------------------------------------------------------------
_SIMILARITY_BASELINE: float = 0.40
_SIMILARITY_SCALE: float = 4.0   # (1.0 - 0.40) * 4.0 * min_weight(0.15) ≈ 0.36 > 0.35


class RiskEngine:
    """
    Score a document for compliance risk using semantic embeddings.

    Reference embeddings are built lazily on the first call to assess() and
    cached for the lifetime of the container (warm Lambda reuse).  This avoids
    making Bedrock calls at module-import time, which simplifies testing and
    keeps cold-start module load fast.
    """

    def __init__(self, bedrock_client=None, s3_client=None) -> None:
        self._client = bedrock_client or boto3.client(
            "bedrock-runtime", region_name=_REGION
        )
        self._s3 = s3_client or boto3.client("s3", region_name=_REGION)
        self._references: dict | None = None  # built on first assess() call

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _embed(self, text: str) -> List[float]:
        """Invoke Cohere Embed and return the embedding vector.

        Cohere Embed accepts a list of texts and returns a list of embeddings.
        We pass a single text and return the first embedding.

        Retries up to _MAX_RETRIES times with exponential backoff + jitter
        on ThrottlingException or ServiceUnavailableException.
        """
        _MAX_RETRIES = 5
        _BASE_DELAY = 1.0  # seconds

        for attempt in range(_MAX_RETRIES):
            try:
                response = self._client.invoke_model(
                    modelId=EMBEDDING_MODEL_ID,
                    body=json.dumps({"texts": [text], "input_type": "search_document"}),
                    contentType="application/json",
                    accept="application/json",
                )
                return json.loads(response["body"].read())["embeddings"][0]
            except Exception as exc:
                error_code = getattr(exc, "response", {}).get("Error", {}).get("Code", "")
                if error_code in ("ThrottlingException", "ServiceUnavailableException") and attempt < _MAX_RETRIES - 1:
                    delay = _BASE_DELAY * (2 ** attempt) + random.uniform(0, 1)
                    logger.warning(
                        "Bedrock throttled (attempt %d/%d), retrying in %.1fs...",
                        attempt + 1, _MAX_RETRIES, delay,
                    )
                    time.sleep(delay)
                else:
                    raise

    def _load_bundled(self) -> Optional[dict]:
        """Load pre-computed reference embeddings from the file bundled with the Lambda."""
        if not os.path.exists(_BUNDLED_EMBEDDINGS_PATH):
            return None
        try:
            with open(_BUNDLED_EMBEDDINGS_PATH) as f:
                data = json.load(f)
            bundled_model = data.get("model_id")
            if bundled_model and bundled_model != EMBEDDING_MODEL_ID:
                logger.warning(
                    "Bundled embeddings were generated with '%s' but current model is '%s' - ignoring.",
                    bundled_model, EMBEDDING_MODEL_ID,
                )
                return None
            logger.info("Loaded reference embeddings from bundled file.")
            return data["categories"]
        except Exception as exc:
            logger.warning("Could not load bundled embeddings: %s", exc)
            return None

    def _load_cache(self) -> Optional[dict]:
        """Try to load pre-computed reference embeddings from S3."""
        if not REFERENCE_CACHE_BUCKET:
            return None
        try:
            response = self._s3.get_object(
                Bucket=REFERENCE_CACHE_BUCKET, Key=REFERENCE_CACHE_KEY
            )
            refs = json.loads(response["Body"].read())
            logger.info("Loaded reference embeddings from S3 cache.")
            return refs
        except Exception:
            return None  # cache miss or S3 unavailable - fall through to Titan

    def _save_cache(self, refs: dict) -> None:
        """Persist reference embeddings to S3 for future cold starts."""
        if not REFERENCE_CACHE_BUCKET:
            return
        try:
            self._s3.put_object(
                Bucket=REFERENCE_CACHE_BUCKET,
                Key=REFERENCE_CACHE_KEY,
                Body=json.dumps(refs),
                ContentType="application/json",
            )
            logger.info("Saved reference embeddings to S3 cache.")
        except Exception as exc:
            logger.warning("Could not save reference embeddings to S3: %s", exc)

    def _build_references(self) -> dict:
        """Load reference embeddings: bundled file → S3 cache → live Titan calls."""
        refs = self._load_bundled()
        if refs is not None:
            return refs

        refs = self._load_cache()
        if refs is not None:
            return refs

        logger.info("Building category reference embeddings via Cohere Embed (first invocation)...")
        refs = {}
        for category, data in RISK_CATEGORIES.items():
            refs[category] = {
                "weight": data["weight"],
                "vector": self._embed(data["reference"]),
            }
            time.sleep(2.0)  # stay within Bedrock's TPS limit between reference calls
        logger.info("Reference embeddings ready for %d categories.", len(refs))

        self._save_cache(refs)
        return refs

    @staticmethod
    def _cosine_similarity(a: List[float], b: List[float]) -> float:
        """Cosine similarity between two vectors; returns 0.0 for zero-norm inputs."""
        dot = sum(x * y for x, y in zip(a, b))
        norm_a = sum(x * x for x in a) ** 0.5
        norm_b = sum(x * x for x in b) ** 0.5
        if norm_a == 0.0 or norm_b == 0.0:
            return 0.0
        return dot / (norm_a * norm_b)

    # ------------------------------------------------------------------
    # Public API  (same interface as the previous keyword engine)
    # ------------------------------------------------------------------

    def assess(self, text: str) -> Tuple[float, List[str]]:
        """
        Score a document for compliance risk.

        Returns
        -------
        score : float in [0.0, 1.0]
        flagged_categories : list[str]
            Categories whose signal (similarity − baseline) was positive,
            sorted alphabetically.

        Scoring model
        -------------
        For each risk category:

            signal       = max(0, cosine_similarity(doc, ref) − _SIMILARITY_BASELINE)
            contribution = signal × _SIMILARITY_SCALE × category_weight

        The baseline removes background semantic similarity that any compliance
        text would naturally share.  _SIMILARITY_SCALE (4.0) is calibrated so
        that a single category with similarity ≥ 0.80 produces a contribution
        above the default RISK_THRESHOLD of 0.35.  The final score is capped
        at 1.0.

        Cohere Embed English v3 accepts up to 2048 characters per text; longer
        documents are truncated to that limit before embedding.
        """
        if not text or not text.strip():
            return 0.0, []

        if self._references is None:
            self._references = self._build_references()

        # Cohere Embed English v3 accepts up to 2048 characters per text
        doc_vector = self._embed(text[:2048])

        total_score = 0.0
        flagged: list = []

        for category, data in self._references.items():
            similarity = self._cosine_similarity(doc_vector, data["vector"])
            signal = max(0.0, similarity - _SIMILARITY_BASELINE)
            contribution = signal * _SIMILARITY_SCALE * data["weight"]
            total_score += contribution

            if signal > 0.0:
                flagged.append(category)

        return min(round(total_score, 6), 1.0), sorted(flagged)
